/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as StatsRouteImport } from './routes/stats'
import { Route as AuthedAdminRouteImport } from './routes/_authed/admin'
import { Route as AuthedChatRouteImport } from './routes/_authed/chat'
import { Route as AuthedHistoryRouteImport } from './routes/_authed/history'
import { Route as AuthedInboxRouteImport } from './routes/_authed/inbox'
import { Route as AuthedNotificationsRouteImport } from './routes/_authed/notifications'
import { Route as AuthedSettingsRouteImport } from './routes/_authed/settings'
import { Route as EIdRouteImport } from './routes/e.$id'
import { Route as GSlugRouteImport } from './routes/g.$slug'
import { Route as UUsernameRouteImport } from './routes/u.$username'
import { Route as UUsernameIndexRouteImport } from './routes/u.$username.index'
import { Route as UUsernameActivityRouteImport } from './routes/u.$username.activity'
import { Route as UUsernameScreenshotsRouteImport } from './routes/u.$username.screenshots'
import { Route as UUsernameStatsRouteImport } from './routes/u.$username.stats'
import { Route as UUsernameWrappedYearRouteImport } from './routes/u.$username.wrapped.$year'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsRoute = StatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedAdminRoute = AuthedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedChatRoute = AuthedChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedHistoryRoute = AuthedHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedInboxRoute = AuthedInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedNotificationsRoute = AuthedNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSettingsRoute = AuthedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthedRoute,
} as any)
const EIdRoute = EIdRouteImport.update({
  id: '/e/$id',
  path: '/e/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const GSlugRoute = GSlugRouteImport.update({
  id: '/g/$slug',
  path: '/g/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const UUsernameRoute = UUsernameRouteImport.update({
  id: '/u/$username',
  path: '/u/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const UUsernameIndexRoute = UUsernameIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => UUsernameRoute,
} as any)
const UUsernameActivityRoute = UUsernameActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => UUsernameRoute,
} as any)
const UUsernameScreenshotsRoute = UUsernameScreenshotsRouteImport.update({
  id: '/screenshots',
  path: '/screenshots',
  getParentRoute: () => UUsernameRoute,
} as any)
const UUsernameStatsRoute = UUsernameStatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => UUsernameRoute,
} as any)
const UUsernameWrappedYearRoute = UUsernameWrappedYearRouteImport.update({
  id: '/wrapped/$year',
  path: '/wrapped/$year',
  getParentRoute: () => UUsernameRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/compare': typeof CompareRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/stats': typeof StatsRoute
  '/admin': typeof AuthedAdminRoute
  '/chat': typeof AuthedChatRoute
  '/history': typeof AuthedHistoryRoute
  '/inbox': typeof AuthedInboxRoute
  '/notifications': typeof AuthedNotificationsRoute
  '/settings': typeof AuthedSettingsRoute
  '/e/$id': typeof EIdRoute
  '/g/$slug': typeof GSlugRoute
  '/u/$username': typeof UUsernameRouteWithChildren
  '/u/$username/activity': typeof UUsernameActivityRoute
  '/u/$username/screenshots': typeof UUsernameScreenshotsRoute
  '/u/$username/stats': typeof UUsernameStatsRoute
  '/u/$username/': typeof UUsernameIndexRoute
  '/u/$username/wrapped/$year': typeof UUsernameWrappedYearRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/compare': typeof CompareRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/stats': typeof StatsRoute
  '/admin': typeof AuthedAdminRoute
  '/chat': typeof AuthedChatRoute
  '/history': typeof AuthedHistoryRoute
  '/inbox': typeof AuthedInboxRoute
  '/notifications': typeof AuthedNotificationsRoute
  '/settings': typeof AuthedSettingsRoute
  '/e/$id': typeof EIdRoute
  '/g/$slug': typeof GSlugRoute
  '/u/$username/activity': typeof UUsernameActivityRoute
  '/u/$username/screenshots': typeof UUsernameScreenshotsRoute
  '/u/$username/stats': typeof UUsernameStatsRoute
  '/u/$username': typeof UUsernameIndexRoute
  '/u/$username/wrapped/$year': typeof UUsernameWrappedYearRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/compare': typeof CompareRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/stats': typeof StatsRoute
  '/_authed/admin': typeof AuthedAdminRoute
  '/_authed/chat': typeof AuthedChatRoute
  '/_authed/history': typeof AuthedHistoryRoute
  '/_authed/inbox': typeof AuthedInboxRoute
  '/_authed/notifications': typeof AuthedNotificationsRoute
  '/_authed/settings': typeof AuthedSettingsRoute
  '/e/$id': typeof EIdRoute
  '/g/$slug': typeof GSlugRoute
  '/u/$username': typeof UUsernameRouteWithChildren
  '/u/$username/activity': typeof UUsernameActivityRoute
  '/u/$username/screenshots': typeof UUsernameScreenshotsRoute
  '/u/$username/stats': typeof UUsernameStatsRoute
  '/u/$username/': typeof UUsernameIndexRoute
  '/u/$username/wrapped/$year': typeof UUsernameWrappedYearRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/compare'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/stats'
    | '/admin'
    | '/chat'
    | '/history'
    | '/inbox'
    | '/notifications'
    | '/settings'
    | '/e/$id'
    | '/g/$slug'
    | '/u/$username'
    | '/u/$username/activity'
    | '/u/$username/screenshots'
    | '/u/$username/stats'
    | '/u/$username/'
    | '/u/$username/wrapped/$year'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/compare'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/stats'
    | '/admin'
    | '/chat'
    | '/history'
    | '/inbox'
    | '/notifications'
    | '/settings'
    | '/e/$id'
    | '/g/$slug'
    | '/u/$username/activity'
    | '/u/$username/screenshots'
    | '/u/$username/stats'
    | '/u/$username'
    | '/u/$username/wrapped/$year'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/compare'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/stats'
    | '/_authed/admin'
    | '/_authed/chat'
    | '/_authed/history'
    | '/_authed/inbox'
    | '/_authed/notifications'
    | '/_authed/settings'
    | '/e/$id'
    | '/g/$slug'
    | '/u/$username'
    | '/u/$username/activity'
    | '/u/$username/screenshots'
    | '/u/$username/stats'
    | '/u/$username/'
    | '/u/$username/wrapped/$year'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  CompareRoute: typeof CompareRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  StatsRoute: typeof StatsRoute
  EIdRoute: typeof EIdRoute
  GSlugRoute: typeof GSlugRoute
  UUsernameRoute: typeof UUsernameRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/admin': {
      id: '/_authed/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthedAdminRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/chat': {
      id: '/_authed/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AuthedChatRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/history': {
      id: '/_authed/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AuthedHistoryRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/inbox': {
      id: '/_authed/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof AuthedInboxRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/notifications': {
      id: '/_authed/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthedNotificationsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/settings': {
      id: '/_authed/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthedSettingsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/e/$id': {
      id: '/e/$id'
      path: '/e/$id'
      fullPath: '/e/$id'
      preLoaderRoute: typeof EIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/g/$slug': {
      id: '/g/$slug'
      path: '/g/$slug'
      fullPath: '/g/$slug'
      preLoaderRoute: typeof GSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$username': {
      id: '/u/$username'
      path: '/u/$username'
      fullPath: '/u/$username'
      preLoaderRoute: typeof UUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$username/': {
      id: '/u/$username/'
      path: '/'
      fullPath: '/u/$username/'
      preLoaderRoute: typeof UUsernameIndexRouteImport
      parentRoute: typeof UUsernameRoute
    }
    '/u/$username/activity': {
      id: '/u/$username/activity'
      path: '/activity'
      fullPath: '/u/$username/activity'
      preLoaderRoute: typeof UUsernameActivityRouteImport
      parentRoute: typeof UUsernameRoute
    }
    '/u/$username/screenshots': {
      id: '/u/$username/screenshots'
      path: '/screenshots'
      fullPath: '/u/$username/screenshots'
      preLoaderRoute: typeof UUsernameScreenshotsRouteImport
      parentRoute: typeof UUsernameRoute
    }
    '/u/$username/stats': {
      id: '/u/$username/stats'
      path: '/stats'
      fullPath: '/u/$username/stats'
      preLoaderRoute: typeof UUsernameStatsRouteImport
      parentRoute: typeof UUsernameRoute
    }
    '/u/$username/wrapped/$year': {
      id: '/u/$username/wrapped/$year'
      path: '/wrapped/$year'
      fullPath: '/u/$username/wrapped/$year'
      preLoaderRoute: typeof UUsernameWrappedYearRouteImport
      parentRoute: typeof UUsernameRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedAdminRoute: typeof AuthedAdminRoute
  AuthedChatRoute: typeof AuthedChatRoute
  AuthedHistoryRoute: typeof AuthedHistoryRoute
  AuthedInboxRoute: typeof AuthedInboxRoute
  AuthedNotificationsRoute: typeof AuthedNotificationsRoute
  AuthedSettingsRoute: typeof AuthedSettingsRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedAdminRoute: AuthedAdminRoute,
  AuthedChatRoute: AuthedChatRoute,
  AuthedHistoryRoute: AuthedHistoryRoute,
  AuthedInboxRoute: AuthedInboxRoute,
  AuthedNotificationsRoute: AuthedNotificationsRoute,
  AuthedSettingsRoute: AuthedSettingsRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

interface UUsernameRouteChildren {
  UUsernameActivityRoute: typeof UUsernameActivityRoute
  UUsernameScreenshotsRoute: typeof UUsernameScreenshotsRoute
  UUsernameStatsRoute: typeof UUsernameStatsRoute
  UUsernameIndexRoute: typeof UUsernameIndexRoute
  UUsernameWrappedYearRoute: typeof UUsernameWrappedYearRoute
}

const UUsernameRouteChildren: UUsernameRouteChildren = {
  UUsernameActivityRoute: UUsernameActivityRoute,
  UUsernameScreenshotsRoute: UUsernameScreenshotsRoute,
  UUsernameStatsRoute: UUsernameStatsRoute,
  UUsernameIndexRoute: UUsernameIndexRoute,
  UUsernameWrappedYearRoute: UUsernameWrappedYearRoute,
}

const UUsernameRouteWithChildren = UUsernameRoute._addFileChildren(
  UUsernameRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  CompareRoute: CompareRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  StatsRoute: StatsRoute,
  EIdRoute: EIdRoute,
  GSlugRoute: GSlugRoute,
  UUsernameRoute: UUsernameRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
