/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as StatsRouteImport } from './routes/stats'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as UsersRouteImport } from './routes/users'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as AuthedAiRouteImport } from './routes/_authed/ai'
import { Route as AuthedChatRouteImport } from './routes/_authed/chat'
import { Route as AuthedHistoryRouteImport } from './routes/_authed/history'
import { Route as AuthedInboxRouteImport } from './routes/_authed/inbox'
import { Route as AuthedNotificationsRouteImport } from './routes/_authed/notifications'
import { Route as AuthedSettingsRouteImport } from './routes/_authed/settings'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAuditRouteImport } from './routes/admin.audit'
import { Route as AdminLogsRouteImport } from './routes/admin.logs'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminStorageRouteImport } from './routes/admin.storage'
import { Route as AdminSystemRouteImport } from './routes/admin.system'
import { Route as EIdRouteImport } from './routes/e.$id'
import { Route as GSlugRouteImport } from './routes/g.$slug'
import { Route as UUsernameRouteImport } from './routes/u.$username'
import { Route as AdminAiIndexRouteImport } from './routes/admin.ai.index'
import { Route as AdminUsersIndexRouteImport } from './routes/admin.users.index'
import { Route as AdminUsersIdRouteImport } from './routes/admin.users.$id'
import { Route as UUsernameIndexRouteImport } from './routes/u.$username.index'
import { Route as UUsernameActivityRouteImport } from './routes/u.$username.activity'
import { Route as UUsernameLibraryRouteImport } from './routes/u.$username.library'
import { Route as UUsernameScreenshotsRouteImport } from './routes/u.$username.screenshots'
import { Route as UUsernameStatsRouteImport } from './routes/u.$username.stats'
import { Route as AdminAiThreadsIdRouteImport } from './routes/admin.ai.threads.$id'
import { Route as AdminAiTracesIndexRouteImport } from './routes/admin.ai.traces.index'
import { Route as AdminAiTracesIdRouteImport } from './routes/admin.ai.traces.$id'
import { Route as UUsernameWrappedYearRouteImport } from './routes/u.$username.wrapped.$year'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsRoute = StatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedAiRoute = AuthedAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedChatRoute = AuthedChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedHistoryRoute = AuthedHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedInboxRoute = AuthedInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedNotificationsRoute = AuthedNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSettingsRoute = AuthedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthedRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLogsRoute = AdminLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStorageRoute = AdminStorageRouteImport.update({
  id: '/storage',
  path: '/storage',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSystemRoute = AdminSystemRouteImport.update({
  id: '/system',
  path: '/system',
  getParentRoute: () => AdminRoute,
} as any)
const EIdRoute = EIdRouteImport.update({
  id: '/e/$id',
  path: '/e/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const GSlugRoute = GSlugRouteImport.update({
  id: '/g/$slug',
  path: '/g/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const UUsernameRoute = UUsernameRouteImport.update({
  id: '/u/$username',
  path: '/u/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAiIndexRoute = AdminAiIndexRouteImport.update({
  id: '/ai/',
  path: '/ai/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersIndexRoute = AdminUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersIdRoute = AdminUsersIdRouteImport.update({
  id: '/users/$id',
  path: '/users/$id',
  getParentRoute: () => AdminRoute,
} as any)
const UUsernameIndexRoute = UUsernameIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => UUsernameRoute,
} as any)
const UUsernameActivityRoute = UUsernameActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => UUsernameRoute,
} as any)
const UUsernameLibraryRoute = UUsernameLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => UUsernameRoute,
} as any)
const UUsernameScreenshotsRoute = UUsernameScreenshotsRouteImport.update({
  id: '/screenshots',
  path: '/screenshots',
  getParentRoute: () => UUsernameRoute,
} as any)
const UUsernameStatsRoute = UUsernameStatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => UUsernameRoute,
} as any)
const AdminAiThreadsIdRoute = AdminAiThreadsIdRouteImport.update({
  id: '/ai/threads/$id',
  path: '/ai/threads/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAiTracesIndexRoute = AdminAiTracesIndexRouteImport.update({
  id: '/ai/traces/',
  path: '/ai/traces/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAiTracesIdRoute = AdminAiTracesIdRouteImport.update({
  id: '/ai/traces/$id',
  path: '/ai/traces/$id',
  getParentRoute: () => AdminRoute,
} as any)
const UUsernameWrappedYearRoute = UUsernameWrappedYearRouteImport.update({
  id: '/wrapped/$year',
  path: '/wrapped/$year',
  getParentRoute: () => UUsernameRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/compare': typeof CompareRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/stats': typeof StatsRoute
  '/terms': typeof TermsRoute
  '/users': typeof UsersRoute
  '/verify-email': typeof VerifyEmailRoute
  '/ai': typeof AuthedAiRoute
  '/chat': typeof AuthedChatRoute
  '/history': typeof AuthedHistoryRoute
  '/inbox': typeof AuthedInboxRoute
  '/notifications': typeof AuthedNotificationsRoute
  '/settings': typeof AuthedSettingsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/storage': typeof AdminStorageRoute
  '/admin/system': typeof AdminSystemRoute
  '/e/$id': typeof EIdRoute
  '/g/$slug': typeof GSlugRoute
  '/u/$username': typeof UUsernameRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/admin/users/$id': typeof AdminUsersIdRoute
  '/u/$username/activity': typeof UUsernameActivityRoute
  '/u/$username/library': typeof UUsernameLibraryRoute
  '/u/$username/screenshots': typeof UUsernameScreenshotsRoute
  '/u/$username/stats': typeof UUsernameStatsRoute
  '/admin/ai/': typeof AdminAiIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
  '/u/$username/': typeof UUsernameIndexRoute
  '/admin/ai/threads/$id': typeof AdminAiThreadsIdRoute
  '/admin/ai/traces/$id': typeof AdminAiTracesIdRoute
  '/u/$username/wrapped/$year': typeof UUsernameWrappedYearRoute
  '/admin/ai/traces/': typeof AdminAiTracesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/compare': typeof CompareRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/stats': typeof StatsRoute
  '/terms': typeof TermsRoute
  '/users': typeof UsersRoute
  '/verify-email': typeof VerifyEmailRoute
  '/ai': typeof AuthedAiRoute
  '/chat': typeof AuthedChatRoute
  '/history': typeof AuthedHistoryRoute
  '/inbox': typeof AuthedInboxRoute
  '/notifications': typeof AuthedNotificationsRoute
  '/settings': typeof AuthedSettingsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/storage': typeof AdminStorageRoute
  '/admin/system': typeof AdminSystemRoute
  '/e/$id': typeof EIdRoute
  '/g/$slug': typeof GSlugRoute
  '/admin': typeof AdminIndexRoute
  '/admin/users/$id': typeof AdminUsersIdRoute
  '/u/$username/activity': typeof UUsernameActivityRoute
  '/u/$username/library': typeof UUsernameLibraryRoute
  '/u/$username/screenshots': typeof UUsernameScreenshotsRoute
  '/u/$username/stats': typeof UUsernameStatsRoute
  '/admin/ai': typeof AdminAiIndexRoute
  '/admin/users': typeof AdminUsersIndexRoute
  '/u/$username': typeof UUsernameIndexRoute
  '/admin/ai/threads/$id': typeof AdminAiThreadsIdRoute
  '/admin/ai/traces/$id': typeof AdminAiTracesIdRoute
  '/u/$username/wrapped/$year': typeof UUsernameWrappedYearRoute
  '/admin/ai/traces': typeof AdminAiTracesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/compare': typeof CompareRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/stats': typeof StatsRoute
  '/terms': typeof TermsRoute
  '/users': typeof UsersRoute
  '/verify-email': typeof VerifyEmailRoute
  '/_authed/ai': typeof AuthedAiRoute
  '/_authed/chat': typeof AuthedChatRoute
  '/_authed/history': typeof AuthedHistoryRoute
  '/_authed/inbox': typeof AuthedInboxRoute
  '/_authed/notifications': typeof AuthedNotificationsRoute
  '/_authed/settings': typeof AuthedSettingsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/storage': typeof AdminStorageRoute
  '/admin/system': typeof AdminSystemRoute
  '/e/$id': typeof EIdRoute
  '/g/$slug': typeof GSlugRoute
  '/u/$username': typeof UUsernameRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/admin/users/$id': typeof AdminUsersIdRoute
  '/u/$username/activity': typeof UUsernameActivityRoute
  '/u/$username/library': typeof UUsernameLibraryRoute
  '/u/$username/screenshots': typeof UUsernameScreenshotsRoute
  '/u/$username/stats': typeof UUsernameStatsRoute
  '/admin/ai/': typeof AdminAiIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
  '/u/$username/': typeof UUsernameIndexRoute
  '/admin/ai/threads/$id': typeof AdminAiThreadsIdRoute
  '/admin/ai/traces/$id': typeof AdminAiTracesIdRoute
  '/u/$username/wrapped/$year': typeof UUsernameWrappedYearRoute
  '/admin/ai/traces/': typeof AdminAiTracesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/compare'
    | '/forgot-password'
    | '/login'
    | '/privacy'
    | '/register'
    | '/reset-password'
    | '/stats'
    | '/terms'
    | '/users'
    | '/verify-email'
    | '/ai'
    | '/chat'
    | '/history'
    | '/inbox'
    | '/notifications'
    | '/settings'
    | '/admin/audit'
    | '/admin/logs'
    | '/admin/reports'
    | '/admin/storage'
    | '/admin/system'
    | '/e/$id'
    | '/g/$slug'
    | '/u/$username'
    | '/admin/'
    | '/admin/users/$id'
    | '/u/$username/activity'
    | '/u/$username/library'
    | '/u/$username/screenshots'
    | '/u/$username/stats'
    | '/admin/ai/'
    | '/admin/users/'
    | '/u/$username/'
    | '/admin/ai/threads/$id'
    | '/admin/ai/traces/$id'
    | '/u/$username/wrapped/$year'
    | '/admin/ai/traces/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/compare'
    | '/forgot-password'
    | '/login'
    | '/privacy'
    | '/register'
    | '/reset-password'
    | '/stats'
    | '/terms'
    | '/users'
    | '/verify-email'
    | '/ai'
    | '/chat'
    | '/history'
    | '/inbox'
    | '/notifications'
    | '/settings'
    | '/admin/audit'
    | '/admin/logs'
    | '/admin/reports'
    | '/admin/storage'
    | '/admin/system'
    | '/e/$id'
    | '/g/$slug'
    | '/admin'
    | '/admin/users/$id'
    | '/u/$username/activity'
    | '/u/$username/library'
    | '/u/$username/screenshots'
    | '/u/$username/stats'
    | '/admin/ai'
    | '/admin/users'
    | '/u/$username'
    | '/admin/ai/threads/$id'
    | '/admin/ai/traces/$id'
    | '/u/$username/wrapped/$year'
    | '/admin/ai/traces'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/admin'
    | '/compare'
    | '/forgot-password'
    | '/login'
    | '/privacy'
    | '/register'
    | '/reset-password'
    | '/stats'
    | '/terms'
    | '/users'
    | '/verify-email'
    | '/_authed/ai'
    | '/_authed/chat'
    | '/_authed/history'
    | '/_authed/inbox'
    | '/_authed/notifications'
    | '/_authed/settings'
    | '/admin/audit'
    | '/admin/logs'
    | '/admin/reports'
    | '/admin/storage'
    | '/admin/system'
    | '/e/$id'
    | '/g/$slug'
    | '/u/$username'
    | '/admin/'
    | '/admin/users/$id'
    | '/u/$username/activity'
    | '/u/$username/library'
    | '/u/$username/screenshots'
    | '/u/$username/stats'
    | '/admin/ai/'
    | '/admin/users/'
    | '/u/$username/'
    | '/admin/ai/threads/$id'
    | '/admin/ai/traces/$id'
    | '/u/$username/wrapped/$year'
    | '/admin/ai/traces/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  CompareRoute: typeof CompareRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  StatsRoute: typeof StatsRoute
  TermsRoute: typeof TermsRoute
  UsersRoute: typeof UsersRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  EIdRoute: typeof EIdRoute
  GSlugRoute: typeof GSlugRoute
  UUsernameRoute: typeof UUsernameRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/ai': {
      id: '/_authed/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AuthedAiRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/chat': {
      id: '/_authed/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AuthedChatRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/history': {
      id: '/_authed/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AuthedHistoryRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/inbox': {
      id: '/_authed/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof AuthedInboxRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/notifications': {
      id: '/_authed/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthedNotificationsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/settings': {
      id: '/_authed/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthedSettingsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/logs': {
      id: '/admin/logs'
      path: '/logs'
      fullPath: '/admin/logs'
      preLoaderRoute: typeof AdminLogsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/storage': {
      id: '/admin/storage'
      path: '/storage'
      fullPath: '/admin/storage'
      preLoaderRoute: typeof AdminStorageRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/system': {
      id: '/admin/system'
      path: '/system'
      fullPath: '/admin/system'
      preLoaderRoute: typeof AdminSystemRouteImport
      parentRoute: typeof AdminRoute
    }
    '/e/$id': {
      id: '/e/$id'
      path: '/e/$id'
      fullPath: '/e/$id'
      preLoaderRoute: typeof EIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/g/$slug': {
      id: '/g/$slug'
      path: '/g/$slug'
      fullPath: '/g/$slug'
      preLoaderRoute: typeof GSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$username': {
      id: '/u/$username'
      path: '/u/$username'
      fullPath: '/u/$username'
      preLoaderRoute: typeof UUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/ai/': {
      id: '/admin/ai/'
      path: '/ai'
      fullPath: '/admin/ai/'
      preLoaderRoute: typeof AdminAiIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users/': {
      id: '/admin/users/'
      path: '/users'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof AdminUsersIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users/$id': {
      id: '/admin/users/$id'
      path: '/users/$id'
      fullPath: '/admin/users/$id'
      preLoaderRoute: typeof AdminUsersIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/u/$username/': {
      id: '/u/$username/'
      path: '/'
      fullPath: '/u/$username/'
      preLoaderRoute: typeof UUsernameIndexRouteImport
      parentRoute: typeof UUsernameRoute
    }
    '/u/$username/activity': {
      id: '/u/$username/activity'
      path: '/activity'
      fullPath: '/u/$username/activity'
      preLoaderRoute: typeof UUsernameActivityRouteImport
      parentRoute: typeof UUsernameRoute
    }
    '/u/$username/library': {
      id: '/u/$username/library'
      path: '/library'
      fullPath: '/u/$username/library'
      preLoaderRoute: typeof UUsernameLibraryRouteImport
      parentRoute: typeof UUsernameRoute
    }
    '/u/$username/screenshots': {
      id: '/u/$username/screenshots'
      path: '/screenshots'
      fullPath: '/u/$username/screenshots'
      preLoaderRoute: typeof UUsernameScreenshotsRouteImport
      parentRoute: typeof UUsernameRoute
    }
    '/u/$username/stats': {
      id: '/u/$username/stats'
      path: '/stats'
      fullPath: '/u/$username/stats'
      preLoaderRoute: typeof UUsernameStatsRouteImport
      parentRoute: typeof UUsernameRoute
    }
    '/admin/ai/threads/$id': {
      id: '/admin/ai/threads/$id'
      path: '/ai/threads/$id'
      fullPath: '/admin/ai/threads/$id'
      preLoaderRoute: typeof AdminAiThreadsIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ai/traces/': {
      id: '/admin/ai/traces/'
      path: '/ai/traces'
      fullPath: '/admin/ai/traces/'
      preLoaderRoute: typeof AdminAiTracesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ai/traces/$id': {
      id: '/admin/ai/traces/$id'
      path: '/ai/traces/$id'
      fullPath: '/admin/ai/traces/$id'
      preLoaderRoute: typeof AdminAiTracesIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/u/$username/wrapped/$year': {
      id: '/u/$username/wrapped/$year'
      path: '/wrapped/$year'
      fullPath: '/u/$username/wrapped/$year'
      preLoaderRoute: typeof UUsernameWrappedYearRouteImport
      parentRoute: typeof UUsernameRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedAiRoute: typeof AuthedAiRoute
  AuthedChatRoute: typeof AuthedChatRoute
  AuthedHistoryRoute: typeof AuthedHistoryRoute
  AuthedInboxRoute: typeof AuthedInboxRoute
  AuthedNotificationsRoute: typeof AuthedNotificationsRoute
  AuthedSettingsRoute: typeof AuthedSettingsRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedAiRoute: AuthedAiRoute,
  AuthedChatRoute: AuthedChatRoute,
  AuthedHistoryRoute: AuthedHistoryRoute,
  AuthedInboxRoute: AuthedInboxRoute,
  AuthedNotificationsRoute: AuthedNotificationsRoute,
  AuthedSettingsRoute: AuthedSettingsRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

interface AdminRouteChildren {
  AdminAuditRoute: typeof AdminAuditRoute
  AdminLogsRoute: typeof AdminLogsRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminStorageRoute: typeof AdminStorageRoute
  AdminSystemRoute: typeof AdminSystemRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminUsersIdRoute: typeof AdminUsersIdRoute
  AdminAiIndexRoute: typeof AdminAiIndexRoute
  AdminUsersIndexRoute: typeof AdminUsersIndexRoute
  AdminAiThreadsIdRoute: typeof AdminAiThreadsIdRoute
  AdminAiTracesIdRoute: typeof AdminAiTracesIdRoute
  AdminAiTracesIndexRoute: typeof AdminAiTracesIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAuditRoute: AdminAuditRoute,
  AdminLogsRoute: AdminLogsRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminStorageRoute: AdminStorageRoute,
  AdminSystemRoute: AdminSystemRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminUsersIdRoute: AdminUsersIdRoute,
  AdminAiIndexRoute: AdminAiIndexRoute,
  AdminUsersIndexRoute: AdminUsersIndexRoute,
  AdminAiThreadsIdRoute: AdminAiThreadsIdRoute,
  AdminAiTracesIdRoute: AdminAiTracesIdRoute,
  AdminAiTracesIndexRoute: AdminAiTracesIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface UUsernameRouteChildren {
  UUsernameActivityRoute: typeof UUsernameActivityRoute
  UUsernameLibraryRoute: typeof UUsernameLibraryRoute
  UUsernameScreenshotsRoute: typeof UUsernameScreenshotsRoute
  UUsernameStatsRoute: typeof UUsernameStatsRoute
  UUsernameIndexRoute: typeof UUsernameIndexRoute
  UUsernameWrappedYearRoute: typeof UUsernameWrappedYearRoute
}

const UUsernameRouteChildren: UUsernameRouteChildren = {
  UUsernameActivityRoute: UUsernameActivityRoute,
  UUsernameLibraryRoute: UUsernameLibraryRoute,
  UUsernameScreenshotsRoute: UUsernameScreenshotsRoute,
  UUsernameStatsRoute: UUsernameStatsRoute,
  UUsernameIndexRoute: UUsernameIndexRoute,
  UUsernameWrappedYearRoute: UUsernameWrappedYearRoute,
}

const UUsernameRouteWithChildren = UUsernameRoute._addFileChildren(
  UUsernameRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  CompareRoute: CompareRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  StatsRoute: StatsRoute,
  TermsRoute: TermsRoute,
  UsersRoute: UsersRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  EIdRoute: EIdRoute,
  GSlugRoute: GSlugRoute,
  UUsernameRoute: UUsernameRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
